all: zadanie_1_03 proces2

include ${CURDIR}/makefile.common

zadanie_1_03.o: zadanie_1_03.c

zadanie_1_03: zadanie_1_03.o

proces2.o: proces2.c

proces2: proces2.o

clean:
	rm -f *.o
	rm -f zadanie_1_03 proces2

